# Generated by Django 3.1.12 on 2021-07-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templatematching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='threshold',
            field=models.FloatField(default=0.95, verbose_name='Match threshold, default 0.95, range:0.0-1.0'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(upload_to='templatematching', verbose_name='Haystack image'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='needle',
            field=models.CharField(blank=True, choices=[('acceptGameButton', 'Accept game button'), ('afterLogINButton', 'After login button(play button)'), ('confirmationButton', 'Confirmation button'), ('findMatchButton', 'Find match button'), ('inQueueFindingMatch', 'In queue finding match text'), ('playGameButton', 'Play game button')], max_length=50, verbose_name='Needle image'),
        ),
        migrations.AddConstraint(
            model_name='uploadedimage',
            constraint=models.CheckConstraint(check=models.Q(('threshold__gte', 0.0), ('threshold__lte', 1.0)), name='A dps value is valid between 0.0 and 1.0'),
        ),
    ]
