# Generated by Django 3.1.12 on 2021-07-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templatematching', '0002_auto_20210701_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='threshold',
            field=models.FloatField(default=0.95, verbose_name='Match threshold, range:0.0-1.0'),
        ),
    ]
