# Generated by Django 3.1.12 on 2021-06-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templatematching', '0002_auto_20210629_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='needle',
            field=models.CharField(blank=True, choices=[('acceptGameButton', 'Accept game button'), ('afterLogINButton', 'After login button(play button)'), ('confirmationButton', 'Confirmation button'), ('findMatchButton', 'Find match button'), ('inQueueFindingMatch', 'In queue finding match text'), ('playGameButton', 'Play game button')], max_length=50),
        ),
    ]
