# Generated by Django 3.1.12 on 2021-06-29 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templatematching', '0003_auto_20210629_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimage',
            name='name',
        ),
    ]
