# Generated by Django 3.1.12 on 2021-06-29 18:39

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templatematching', '0004_remove_uploadedimage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='id', unique=True, verbose_name='Uploaded Image address'),
        ),
    ]
