# Generated by Django 3.1.12 on 2021-06-29 19:30

import autoslug.fields
from django.db import migrations
import portfolio.templatematching.models


class Migration(migrations.Migration):

    dependencies = [
        ('templatematching', '0005_auto_20210629_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=portfolio.templatematching.models.UploadedImage.populate_slug, unique=True, verbose_name='Uploaded Image address'),
        ),
    ]
