# Generated by Django 3.1.12 on 2021-06-24 08:52

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of champion')),
                ('dps', models.IntegerField()),
                ('attackspeed', models.FloatField()),
                ('dmg', models.IntegerField()),
                ('range', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven')])),
                ('hp', models.IntegerField()),
                ('mana', models.IntegerField()),
                ('armor', models.IntegerField()),
                ('mr', models.IntegerField()),
                ('origin_prim', models.CharField(max_length=30)),
                ('origin_sec', models.CharField(max_length=30)),
                ('class_prim', models.CharField(max_length=30)),
                ('class_sec', models.CharField(max_length=30)),
                ('cost', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven')])),
                ('tier', models.IntegerField(choices=[(1, 'D'), (2, 'C'), (3, 'B'), (4, 'A'), (5, 'S')])),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='Champion name')),
            ],
        ),
        migrations.AddConstraint(
            model_name='champion',
            constraint=models.CheckConstraint(check=models.Q(('dps__gte', 0), ('dps__lte', 800)), name='A dps value is valid between 0 and 800'),
        ),
        migrations.AddConstraint(
            model_name='champion',
            constraint=models.CheckConstraint(check=models.Q(('attackspeed__gte', 0.0), ('attackspeed__lte', 8.0)), name='An attackspeed value is valid between 0.0 and 8.0'),
        ),
        migrations.AddConstraint(
            model_name='champion',
            constraint=models.CheckConstraint(check=models.Q(('dmg__gte', 0), ('dmg__lte', 500)), name='A dmg value is valid between 0 and 500'),
        ),
        migrations.AddConstraint(
            model_name='champion',
            constraint=models.CheckConstraint(check=models.Q(('hp__gte', 0), ('hp__lte', 5000)), name='A hp value is valid between 0 and 5000'),
        ),
        migrations.AddConstraint(
            model_name='champion',
            constraint=models.CheckConstraint(check=models.Q(('mana__gte', 0), ('mana__lte', 300)), name='A mana value is valid between 0 and 300'),
        ),
        migrations.AddConstraint(
            model_name='champion',
            constraint=models.CheckConstraint(check=models.Q(('armor__gte', 0), ('armor__lte', 300)), name='AN armor value is valid between 0 and 300'),
        ),
        migrations.AddConstraint(
            model_name='champion',
            constraint=models.CheckConstraint(check=models.Q(('mr__gte', 0), ('mr__lte', 300)), name='A mr value is valid between 0 and 300'),
        ),
    ]
