# Generated by Django 3.1.12 on 2021-06-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tftchampions', '0003_auto_20210624_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='armor',
            field=models.IntegerField(verbose_name='Armor of champion'),
        ),
        migrations.AlterField(
            model_name='champion',
            name='attackspeed',
            field=models.FloatField(verbose_name='Attack speed of champion'),
        ),
        migrations.AlterField(
            model_name='champion',
            name='class_prim',
            field=models.CharField(max_length=30, verbose_name='Class primary of champion'),
        ),
        migrations.AlterField(
            model_name='champion',
            name='class_sec',
            field=models.CharField(max_length=30, verbose_name='Class secondary of champion'),
        ),
        migrations.AlterField(
            model_name='champion',
            name='cost',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven')], verbose_name='Cost of champion'),
        ),
        migrations.AlterField(
            model_name='champion',
            name='dmg',
            field=models.IntegerField(verbose_name='Damage of champion'),
        ),
        migrations.AlterField(
            model_name='champion',
            name='dps',
            field=models.IntegerField(verbose_name='Damage per second(dmg*attackspeed) of champion'),
        ),
        migrations.AlterField(
            model_name='champion',
            name='hp',
            field=models.IntegerField(verbose_name='Health points of champion'),
        ),
        migrations.AlterField(
            model_name='champion',
            name='mana',
            field=models.IntegerField(verbose_name='Mana points of champion'),
        ),
        migrations.AlterField(
            model_name='champion',
            name='mr',
            field=models.IntegerField(verbose_name='Magic resistance of champion'),
        ),
        migrations.AlterField(
            model_name='champion',
            name='origin_prim',
            field=models.CharField(max_length=30, verbose_name='Origin primary of champion'),
        ),
        migrations.AlterField(
            model_name='champion',
            name='origin_sec',
            field=models.CharField(max_length=30, verbose_name='Origin secondary of champion'),
        ),
        migrations.AlterField(
            model_name='champion',
            name='range',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven')], verbose_name='Range of champion in hexes'),
        ),
        migrations.AlterField(
            model_name='champion',
            name='tier',
            field=models.IntegerField(choices=[(1, 'D'), (2, 'C'), (3, 'B'), (4, 'A'), (5, 'S')], verbose_name='Tier of champion'),
        ),
    ]
