# Generated by Django 3.1.12 on 2021-06-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioproject',
            name='try_online_url',
            field=models.URLField(blank=True),
        ),
    ]
